export default [
  {
    id: 1,
    title: "白水晶素手串",
    note: "純淨透亮的白水晶，簡約而不簡單，適合日常配戴",
    description: "白水晶是最純淨的水晶，能夠淨化負能量，帶來正向能量。",
    forPerson: "適合所有人配戴",
    crystal_size: "8mm",
    head_size: "14-16cm",
    price: "NT$ 600",
    imgUrl: "https://i.imgur.com/tPuVTAZ.jpeg",
    imgUrlSamll: "https://i.imgur.com/tPuVTAZ.jpeg",
    type: "simple"
  },
  {
    id: 2,
    title: "粉晶素手串",
    note: "溫柔粉嫩的粉水晶，招桃花、增進人際關係",
    description: "粉晶又稱芙蓉晶，是愛情之石，能增加異性緣與人際關係。",
    forPerson: "適合想要提升人緣與桃花運的人",
    crystal_size: "8mm",
    head_size: "14-16cm",
    price: "NT$ 650",
    imgUrl: "https://i.imgur.com/gdQvu9y.png",
    imgUrlSamll: "https://i.imgur.com/gdQvu9y.png",
    type: "simple"
  },
  {
    id: 3,
    title: "紫水晶素手串",
    note: "高貴典雅的紫水晶，增加智慧與靈性",
    description: "紫水晶能開發智慧，幫助思考，提升靈性與直覺力。",
    forPerson: "適合需要靈感與創意的人",
    crystal_size: "8mm",
    head_size: "14-16cm",
    price: "NT$ 700",
    imgUrl: "https://i.imgur.com/WQuzfuy.jpeg",
    imgUrlSamll: "https://i.imgur.com/WQuzfuy.jpeg",
    type: "simple"
  },
  {
    id: 4,
    title: "黃水晶素手串",
    note: "明亮的黃水晶，招財聚氣，提升正能量",
    description: "黃水晶是招財石，能帶來財運與好運氣。",
    forPerson: "適合想要提升財運的人",
    crystal_size: "8mm",
    head_size: "14-16cm",
    price: "NT$ 680",
    imgUrl: "https://i.imgur.com/GduXnt8.jpeg",
    imgUrlSamll: "https://i.imgur.com/GduXnt8.jpeg",
    type: "simple"
  },
  {
    id: 5,
    title: "黑曜石素手串",
    note: "強大的保護石，辟邪化煞，排除負能量",
    description: "黑曜石具有強大的保護作用，能辟邪化煞，排除負能量。",
    forPerson: "適合需要保護與安定的人",
    crystal_size: "8mm",
    head_size: "14-16cm",
    price: "NT$ 550",
    imgUrl: "https://i.imgur.com/JuNdJxp.jpeg",
    imgUrlSamll: "https://i.imgur.com/JuNdJxp.jpeg",
    type: "simple"
  },
  {
    id: 6,
    title: "草莓晶素手串",
    note: "甜美的草莓晶，招桃花愛情，增強人緣",
    description: "草莓晶能招桃花與愛情運，增強個人魅力。",
    forPerson: "適合想要感情順利的人",
    crystal_size: "8mm",
    head_size: "14-16cm",
    price: "NT$ 720",
    imgUrl: "https://i.imgur.com/tPuVTAZ.jpeg",
    imgUrlSamll: "https://i.imgur.com/tPuVTAZ.jpeg",
    type: "simple"
  },
  {
    id: 7,
    title: "青金石素手串",
    note: "深邃的藍色青金石，開發智慧，增強直覺",
    description: "青金石能開發智慧、增強記憶力與直覺力。",
    forPerson: "適合學生與需要思考的人",
    crystal_size: "8mm",
    head_size: "14-16cm",
    price: "NT$ 800",
    imgUrl: "https://i.imgur.com/gdQvu9y.png",
    imgUrlSamll: "https://i.imgur.com/gdQvu9y.png",
    type: "simple"
  },
  {
    id: 8,
    title: "綠東陵素手串",
    note: "清新的綠色，招財納福，舒緩情緒",
    description: "綠東陵能招財納福，舒緩緊張情緒，帶來好運。",
    forPerson: "適合想要平靜心情的人",
    crystal_size: "8mm",
    head_size: "14-16cm",
    price: "NT$ 580",
    imgUrl: "https://i.imgur.com/WQuzfuy.jpeg",
    imgUrlSamll: "https://i.imgur.com/WQuzfuy.jpeg",
    type: "simple"
  },
  {
    id: 9,
    title: "茶晶素手串",
    note: "沉穩的茶色水晶，安定情緒，增強行動力",
    description: "茶晶能安定情緒，增強實踐力與行動力。",
    forPerson: "適合需要穩定能量的人",
    crystal_size: "8mm",
    head_size: "14-16cm",
    price: "NT$ 620",
    imgUrl: "https://i.imgur.com/GduXnt8.jpeg",
    imgUrlSamll: "https://i.imgur.com/GduXnt8.jpeg",
    type: "simple"
  },
  {
    id: 10,
    title: "海藍寶素手串",
    note: "如海水般清澈的藍色，增加溝通能力與勇氣",
    description: "海藍寶能增加溝通表達能力，帶來勇氣與自信。",
    forPerson: "適合需要表達與溝通的人",
    crystal_size: "8mm",
    head_size: "14-16cm",
    price: "NT$ 850",
    imgUrl: "https://i.imgur.com/JuNdJxp.jpeg",
    imgUrlSamll: "https://i.imgur.com/JuNdJxp.jpeg",
    type: "simple"
  },
  {
    id: 11,
    title: "紅瑪瑙素手串",
    note: "熱情的紅瑪瑙，增強活力與行動力",
    description: "紅瑪瑙能增強活力、激發熱情與行動力。",
    forPerson: "適合需要動力與熱情的人",
    crystal_size: "8mm",
    head_size: "14-16cm",
    price: "NT$ 600",
    imgUrl: "https://i.imgur.com/tPuVTAZ.jpeg",
    imgUrlSamll: "https://i.imgur.com/tPuVTAZ.jpeg",
    type: "simple"
  },
  {
    id: 12,
    title: "月光石素手串",
    note: "柔和的月光石，平衡情緒，增加女性魅力",
    description: "月光石能平衡情緒，增加女性魅力與柔和氣質。",
    forPerson: "特別適合女性配戴",
    crystal_size: "8mm",
    head_size: "14-16cm",
    price: "NT$ 780",
    imgUrl: "https://i.imgur.com/gdQvu9y.png",
    imgUrlSamll: "https://i.imgur.com/gdQvu9y.png",
    type: "simple"
  }
];
